spring.application.name=back


spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT settings
jwt.secret=your-very-secure-random-secret-key-at-least-32-chars-long
jwt.expiration=86400000